version: '3'
services:
 db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports: 
      - 54320:5432
    volumes:
       - ./db/:/var/lib/postgresql/data